version: '3.1'

services:
  cert:
    build: .
    container_name: shell
    environment:
      DOMAINS1: ${DOMAINS1}
      DOMAINS2: ${DOMAINS2}
      EXPIRE: ${EXPIRE}
      BFDAY: ${BFDAY}
      TZ: Asia/Tokyo
    volumes:
    #  - ./cron.log:/var/log/cron.log
      - ./shellscript.sh:/shellscript.sh
      - ./_.masa-nakajima.com.crt:/tmp/_.masa-nakajima.com.crt