version: '3.1'

services:
  cert:
    build: .
    container_name: shell
    environment:
      DOMAINS: ${DOMAINS}
      EXPIRE: ${EXPIRE}
      BFDAY: ${BFDAY}
      TZ: Asia/Tokyo
    volumes:
    #  - ./cron.log:/var/log/cron.log
      - ./shellscript.sh:/shellscript.sh
      - ./_.sample.crt:/tmp/_.sample.com.crt
  web:
    image: nginx:1.18.0-alpine
    container_name: websrv2
    restart: always
    ports:
      - 80:80
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - cert

