version: '3.1'

services:
  web:
    build: ./web
    container_name: websrv2
    restart: always
    environment:
      DOMAINS: ${DOMAINS}
      EXPIRE: ${EXPIRE}
      BFDAY: ${BFDAY}
      TZ: Asia/Tokyo
    volumes:
      - ./web/cert/_.sample.crt:/tmp/_.sample.com.crt
      - ./web/cert/shellscript.sh:/tmp/shellscript.sh
      - ./web/cert/shellscript.log:/tmp/shellscript.log
    ports:
      - 80:80

