FROM nginx:1.18.0-alpine

RUN apk add --no-cache lego supervisor

COPY /cert/cron-setting /etc/cron.d/cron-setting
COPY /cert/shellscript.sh /tmp/shellscript.sh
COPY /cert/shellscript.log /tmp/shellscript.log
COPY /app.conf /etc/supervisord/conf.d/app.conf

RUN chmod 0644 /etc/cron.d/cron-setting
RUN chmod 0744 /tmp/shellscript.sh
RUN chmod 0644 /tmp/shellscript.log
RUN crontab /etc/cron.d/cron-setting

# CMD ["crond", "-f"]
CMD [ "/usr/bin/supervisord", "-c", "/etc/supervisord/conf.d/app.conf" ]